spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/antra_e_commerce_db_user
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

aws:
  region: ${AWS_REGION}
  dynamodb:
    table:
      address: ${DYNAMODB_ADDRESS_TABLE}