spring:
  application:
    name: order-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8084

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"

cognito:
  issuerUri: ${COGNITO_ISSUERURI}